version: '3.8'

services:
    automx2:
        image: harbor-registry.atlantishq.de/beekama/mail-autoconfig:latest
        container_name: automail
        restart: always
        ports: 
            - "4243:4243"   # flask port
        volumes:
             - ./init.sql:/home/automx2/init.sql
             - /data/automail-db/:/data/automx2/  # persistent databse
        environment:
            - FLASK_ENV=production
            - FLASK_APP=automx2.server:app
