name: Container Build

on:
    push:
        branches:
            - "main"

jobs:
    docker:
        runs-on: debian
        environment:
            name: prod
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Login to Docker Registry
              uses: docker/login-action@v2
              with:
                registry: ${{ secrets.REGISTRY }}
                username: ${{ secrets.REGISTRY_USER }}
                password: ${{ secrets.REGISTRY_PASS }}

            - name: Build and Push Docker Image
              uses: docker/build-push-action@v3
              with:
                context: .
                platforms: linux/amd64
                push: true
                tags: "${{ secrets.REGISTRY }}/beekama/mail-autoconfig:latest"
